#!/usr/bin/env python
import os, sys
from kazoo.client import KazooClient

if len(sys.argv) < 3:
    print "Usage: zkput.py zkhost:port remote-path"
    sys.exit(1)

zk = KazooClient(hosts=sys.argv[1])
zk.start()
for x in zk.get_children(sys.argv[2]):
    print x
