#!/usr/bin/env python
import os, sys
from kazoo.client import KazooClient

if len(sys.argv) < 4:
    print "Usage: zkput.py zkhost:port local-path remote-path"
    sys.exit(1)

zk = KazooClient(hosts=sys.argv[1])
zk.start()
zk.set(sys.argv[3], open(sys.argv[2]).read())
